-- setup

CREATE USER app_read WITH PASSWORD 'FybkRj3KaadDfab';
CREATE USER app_dml WITH PASSWORD 'pkvtvP-aQ8ST6ff';
CREATE USER app WITH PASSWORD 'P4fjcufPsQ@7M?6';

ALTER USER postgres WITH PASSWORD 'uYdCK6LgE8aE]8?M\?8f';

CREATE DATABASE scriptmime WITH OWNER app;


# RESET DEFAULT PERMISSIONS

REVOKE ALL ON SCHEMA public FROM public;

GRANT USAGE ON SCHEMA public TO public;


#GRANT PERMISSIONS TO APP_READ

GRANT SELECT
	ON ALL TABLES IN SCHEMA public
	TO app_read;


ALTER DEFAULT PRIVILEGES IN SCHEMA public
	GRANT SELECT ON TABLES
	TO app_read;

#GRANT PERMISSIONS TO APP_DML

GRANT SELECT, INSERT, UPDATE, DELETE
	ON ALL TABLES IN SCHEMA public
	TO app_dml;


ALTER DEFAULT PRIVILEGES IN SCHEMA public
	GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES
	TO app_dml;


